\hypertarget{class_sabre_1_1_event_1_1_promise_already_resolved_exception}{}\section{Sabre\textbackslash{}Event\textbackslash{}Promise\+Already\+Resolved\+Exception Klassenreferenz}
\label{class_sabre_1_1_event_1_1_promise_already_resolved_exception}\index{Sabre\textbackslash{}\+Event\textbackslash{}\+Promise\+Already\+Resolved\+Exception@{Sabre\textbackslash{}\+Event\textbackslash{}\+Promise\+Already\+Resolved\+Exception}}
Klassendiagramm für Sabre\textbackslash{}Event\textbackslash{}Promise\+Already\+Resolved\+Exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{class_sabre_1_1_event_1_1_promise_already_resolved_exception}
\end{center}
\end{figure}


\subsection{Ausführliche Beschreibung}
This exception is thrown when the user tried to reject or fulfill a promise, after either of these actions were already performed.

\begin{DoxyCopyright}{Copyright}
Copyright (C) 2013-\/2015 fruux GmbH (\href{https://fruux.com/}{\tt https\+://fruux.\+com/}). 
\end{DoxyCopyright}
\begin{DoxyAuthor}{Autor}
Evert Pot (\href{http://evertpot.com/}{\tt http\+://evertpot.\+com/})  \href{http://sabre.io/license/}{\tt http\+://sabre.\+io/license/} Modified B\+SD License 
\end{DoxyAuthor}


Definiert in Zeile 13 der Datei Promise\+Already\+Resolved\+Exception.\+php.



Die Dokumentation für diese Klasse wurde erzeugt aufgrund der Datei\+:\begin{DoxyCompactItemize}
\item 
Upload/framework/lib/webdav/\+Sabre\+D\+A\+V/vendor/sabre/event/lib/Promise\+Already\+Resolved\+Exception.\+php\end{DoxyCompactItemize}
